# Date: 2018-02-14
rm(list=ls())
require(tidyr)
require(dplyr)
require(data.table)
require(lattice)
require(ggplot2)
require(ggpubr)
require(maptools)
require(raster)
require(rgdal)
require(zyp)
require(ggplot2)
require(randomForest)
require(ranger)
require(caret) # confusionMatrix() and train()
require(pdp) # partial dependency plots

citation("tidyr")
citation("dplyr")
citation("data.table")
citation("lattice")
citation("ggplot2")
citation("ggpubr")
citation("maptools")
citation("raster")
citation("rgdal")
citation("zyp")
citation("ggplot2")
citation("randomForest")
citation("caret")
citation("rgdal")

packageVersion("tidyr")
packageVersion("dplyr")
packageVersion("data.table")
packageVersion("lattice")
packageVersion("ggplot2")
packageVersion("ggpubr")
packageVersion("maptools")
packageVersion("raster")
packageVersion("rgdal")
packageVersion("zyp")
packageVersion("ggplot2")
packageVersion("randomForest")
packageVersion("ranger")
packageVersion("pdp")
packageVersion("caret")
